language: go

go:
  - 1.15.x

script:
  - make lint
  - make test-unit
  - make build
  - make build-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash scripts/publish-docker.sh
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
